apiVersion: v1
kind: Service
metadata: 
  name: nodeservice
spec: 
  type: ClusterIP
  ports: 
    - port: 8080     
      targetPort: 8080     
  selector:
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: server
spec: 
  replicas: 1

  selector: 
    matchLabels: 
      tier: backend
  template: 
    metadata: 
      labels: 
        tier: backend
    spec: 
      containers: 
        - image: "si3mshady/strayaway-be:1.3.8"
          name: nodeservice
          ports: 
            - containerPort: 8080
              hostPort: 8080
