--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      tier: frontend
  template: 
    metadata: 
      labels: 
        tier: frontend
    spec: 
      containers: 
        - 
          image: "si3mshady/strayaway-fe:1.3.8"
          name: reactfrontend
          ports: 
            - 
              containerPort: 80
              

---
apiVersion: v1
kind: Service
metadata: 
  name: reactfrontend #service dns name
spec:
  type: NodePort
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30300
  selector: 
    tier: frontend    
    
