apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium
spec:
  replicas: 2
  selector:
    matchLabels:
      # manage pods with the label app: selenium 
      app: selenium      
  template:
    metadata:
      labels:
        app: selenium        
    spec:
      containers:
      - name: selenium
        image: selenium/standalone-chrome:4.0.0-beta-1-20210215
        ports:
        - containerPort: 4444
          # hostPort: 4444
--- 
apiVersion: v1
kind: Service
metadata: 
  name: selenium #service dns name
spec: 
  ports: 
    - port: 4444
      targetPort: 4444
    
  selector: 
    app: selenium    
  type: ClusterIP