version: "3.7"  # optional since v1.27.0
services:
  #reactApp
  strayAway:
    image: si3mshady/strayaway:1.3
    ports: 
      - "5000:888"
              
  server:
    #accepts get request to trigger automation 
    build: .
    ports:
      - "8080:8080"             
  selenium:
    image: selenium/standalone-chrome:4.0.0-beta-1-20210215
    ports:
      - "4444:4444"
    
